version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ats-web
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ats-data:/app/data
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ats_db?schema=public
    restart: unless-stopped
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ats-worker
    command: node worker.js
    volumes:
      - ats-data:/app/data
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ats_db?schema=public
    restart: unless-stopped
    depends_on:
      - web
      - db

  db:
    image: postgres:15-alpine
    container_name: ats-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ats_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ats-redis
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  ats-data:
    name: ats-shared-data
  pgdata:
    name: ats-postgres-data
  redisdata:
    name: ats-redis-data
